name: Linter

on:
  push:
    branches:
      - 'BIT-1998**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint Code Base
      # uses: github/super-linter/slim@v4
      uses: dyingAngel/super-linter/slim@v4
      env:
        # Need to reset? the GOROOT if using actions/setup-go@v1
        # GOROOT:
        ACTIONS_RUNNER_DEBUG: true
        VALIDATE_GO: true
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}